/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../src/components/layout/tabbar/breadcrumb/index.vue')['default']
    CusForm: typeof import('./../src/components/package/form/CusForm.vue')['default']
    Logo: typeof import('./../src/components/layout/logo/index.vue')['default']
    Menu: typeof import('./../src/components/layout/menu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    Routerview: typeof import('./../src/components/layout/routerview/index.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./../src/components/layout/tabbar/setting/index.vue')['default']
    SvgIcon: typeof import('./../src/components/package/svgIcon/index.vue')['default']
    Tabbar: typeof import('./../src/components/layout/tabbar/index.vue')['default']
  }
}
